### ISSUE TITLE
App does not erase all EXIF metadata (MacOs)

### ISSUE THREAD

**Issue by Science-G** [LoicPandul/ImagesConverter#6]
I used ExifCleaner (https://github.com/szTheory/exifcleaner) to check whether the application does its job of deleting EXIF metadata, and it seems that ImagesConverter leaves at least some metadata in the images.

**Image after ImagesConverter:**
![Screenshot 2024-04-05 at 5 56 21 AM](https://github.com/LoicPandul/ImagesConverter/assets/137571657/dabd12d3-26e4-463b-92ec-c77f4372dede)

**Image after ExifCleaner:**
![Screenshot 2024-04-05 at 5 56 21 AM](https://github.com/LoicPandul/ImagesConverter/assets/137571657/aac2e2a0-528e-46d7-aed2-6170ce7fec2a)

**ExifCleaner report:**
<img width="575" alt="Screenshot 2024-04-05 at 6 01 38 AM" src="https://github.com/LoicPandul/ImagesConverter/assets/137571657/4ebc28d4-d493-4839-b650-19fd1473196b">

---

We might want to have a deeper look into the source code of ExifCleaner to make that ImagesConverter safe regarding metadata. Another great argument for the upcoming fundraising.

**Comment by LoicPandul** [comment]
C'est bizarre, parce que dans tous les tests que j'ai faits personnellement avec exiftool d'un côté et mon logiciel de l'autre, les mêmes métadonnées étaient bien supprimées. Mais effectivement, avec ton exemple, ça ne fonctionne pas entièrement.

J'ai essayé avec d'autres bibliothèques python et ça me donne le même résultat. Il faudrait directement intégrer exiftool, mais c'est trop compliqué pour ce petit projet ^^ 

Néanmoins, je me demande à quel point ce serait important de supprimer ces métadonnées sur ton image. Je pense même que c'est mon logiciel qui les génère parce que la fonction `clean_metadata` extrait uniquement les données pixel de l'image et recréer une image depuis zéro en y insérant les données pixel.

**Comment by pythcoiner** [comment]
what need to be checked btw, it's maybe we adding some metadata....

**Comment by LoicPandul** [comment]
Je viens de comparer dans le détail la différence dans les métadonnées entre les 2 images (avec ImagesConverter VS avec ExifCleaner). Voici les 4 métadonnées non supprimées avec mon logiciel : 

- `JFIFVersion`
- `ResolutionUnit`
- `XResolution`
- `YResolution`

Ce sont des données exclusivement techniques et pas sensibles dans un souci de confidentialité. `JFIFVersion` correspond à la version du format de fichier. `ResolutionUnit` est paramétré sur `None` alors qu'avec ExifCleaner, il est supprimé. `XResolution` et `YResolution` désignent le nombre de pixels par unité sur les axes horizontal et vertical.

Ces différences ne sont donc pas très préoccupantes imo. Je ferme l'issue, mais je te remercie de me l'avoir signalé 👍
